[build]
  publish = "dist"
  command = "gridsome build"

[template.environment]
  WORDPRESS_URL = "https://api.joshcollinsworth.com"

# ---
# Redirects
# ---

[[redirects]]
  from = "/wp-content/uploads/*"
  to = "/assets/images/uploads/:splat"
  status = 301

[[redirects]]
  from = "/feed"
  to = "https://api.joshcollinsworth.com/feed/"
  status = 301

[[redirects]]
  from = "/essential"
  to = "/essential-tools-wordpress-development/"
  status = 301

# ---
# Headers
# ---

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
