[build]
  publish = "dist"
  command = "gridsome build"

[template.environment]
  WORDPRESS_URL = "https://api.joshcollinsworth.com"

[[redirects]]
  from = "/wp-content/uploads/*"
  to = "/assets/images/uploads/:splat"
