[build]
  publish = "dist"
  command = "gridsome build"

[template.environment]
  WORDPRESS_URL = "https://api.joshcollinsworth.com"

[[redirects]]
  from = "/wp-content/uploads/*"
  to = "/assets/images/uploads/:splat"
  status = 301

[[redirects]]
  from = "/feed"
  to = "https://api.joshcollinsworth.com/feed/"
  status = 301

[[redirects]]
  from = "/essential"
  to = "/essential-tools-wordpress-development/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.png" # css files too
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.jpg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=2592000"
