[build]
  publish = "dist"
  command = "gridsome build"

[template.environment]
  WORDPRESS_URL = "https://api.joshcollinsworth.com"

[[redirects]]
  from = "/wp-content/uploads/*"
  to = "/assets/images/uploads/:splat"
  status = 301

[[redirects]]
  from = "/feed"
  to = "https://api.joshcollinsworth.com/feed/"
  status = 301

[[redirects]]
  from = "/essential"
  to = "/essential-tools-wordpress-development/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
